#!/usr/bin/env python
"""
Writes the grn/ctx run CSVs automatically, instead of hand-writing rows
for every TF.

Run once per experiment/data drop. Two ways to use it:

  Interactive (no arguments) — asks for each value, with sensible defaults
  you can accept by just pressing Enter:

    python scripts/generate_configs.py

  Non-interactive (pass --data-dir) — for scripting/automation/repeat runs,
  skips all prompts:

    python scripts/generate_configs.py --data-dir my_data --project my_project --run-id my_experiment --num-workers 4

What it looks for inside the data folder (recursively):
  - one .loom file                          -> expression matrix
  - one TF list file matching *tfs*.txt     -> candidate regulators for grn
  - .feather files matching --feather-regex -> one per TF, for ctx
  - .tbl files matching --tbl-regex         -> one per TF, for ctx

A TF is included in ctx_runs.local.csv only if BOTH its .feather and its
.tbl file were found; TFs with only one of the two are skipped with a
warning (nothing silently wrong is written).

If exactly one extra .feather/.tbl pair is found that does NOT match a TF
(a plain, genome-wide cisTarget database, not tied to any single TF), it's
added as one extra "motifs_only" baseline row per replicate, run before the
per-TF rows — pass --no-baseline to skip this even if such a pair exists.

Pass --replicates N (default 1) to run grn N independent times (grnboost2
has no fixed random seed, so each run naturally differs) and cross each
replicate's adjacency with every TF for ctx — e.g. --replicates 30 with 14
TFs writes 30 grn rows and 30*14=420 ctx rows.

Every run of this script writes a new, timestamped pair of files into a
stable configs/ folder — nothing is ever overwritten, so the full history of
every config you've generated stays on disk for auditing. logs/ and outs/
(pyscenic's own adj/, regs/) are siblings of that configs/ folder, so
everything about one project/cell-line — what you asked for, what happened,
and what came out — lives together under one artifacts/<project>/ folder:

    artifacts/<project>/[<cell-line>/]configs/grn_runs_<timestamp>.local.csv
    artifacts/<project>/[<cell-line>/]configs/ctx_runs_<timestamp>.local.csv
    artifacts/<project>/[<cell-line>/]logs/...
    artifacts/<project>/[<cell-line>/]outs/adj/...
    artifacts/<project>/[<cell-line>/]outs/regs/...

--project groups related runs together (e.g. all canonical-TF work);
--cell-line is optional and adds one more level of grouping (e.g. 'HepG2',
'K562'). These generated *.local.csv files are the ones
scripts/run_pyscenic_grn.sh and scripts/run_pyscenic_ctx.sh take as an
argument, and the whole artifacts/<project>/ tree is gitignored — it holds
real, machine-specific paths and run outputs, never meant to be committed.
artifacts/examples/*.example.csv is a separate thing: tracked, safe-to-share
templates for the smoke test, not generated by this script.
"""
import argparse
import csv
import re
import sys
from datetime import datetime
from pathlib import Path

DEFAULT_FEATHER_REGEX = r"motifs_plus_([A-Za-z0-9]+)\.genes_vs_motifs\.rankings\.feather$"
DEFAULT_TBL_REGEX = r"pptf_([A-Za-z0-9]+)\.tbl$"
DEFAULT_TFS_GLOB = "*tfs*.txt"
# Readable, still-sortable timestamp for filenames, e.g. 2026-09-08_21-02-00.
TIMESTAMP_FORMAT = "%Y-%m-%d_%H-%M-%S"


def slugify(value: str) -> str:
    """Makes a string safe to use as a single path component, and
    normalizes case — used for --project/--cell-line specifically so
    'HepG2', 'hepg2', and 'HEPG2' all land in the exact same folder instead
    of silently creating three different ones."""
    return re.sub(r"[^A-Za-z0-9_-]+", "_", value.strip()).strip("_").lower()


def scoped_dir(root: str, project: str, cell_line: str | None) -> Path:
    """A stable folder scoped by project (optionally, cell line) under
    `root`: <root>/<project>/[<cell-line>/]. Repeated runs add new
    timestamped config files there rather than new folders — and the same
    folder also holds that project/cell-line's logs and pyscenic outputs
    (adj/, regs/), so everything about one project stays in one place."""
    parts = [Path(root), slugify(project)]
    if cell_line:
        parts.append(slugify(cell_line))
    return Path(*parts)


def artifact_dir_for(project: str, cell_line: str | None) -> Path:
    return scoped_dir("artifacts", project, cell_line)


def config_filenames(when: datetime | None = None) -> tuple[str, str]:
    """(grn_filename, ctx_filename) for a run happening at `when` (default:
    now) — e.g. ('grn_runs_2026-09-08_21-02-00.local.csv', 'ctx_runs_...')."""
    timestamp = (when or datetime.now()).strftime(TIMESTAMP_FORMAT)
    return f"grn_runs_{timestamp}.local.csv", f"ctx_runs_{timestamp}.local.csv"


def ask(question: str, default: str | None = None, validate=None) -> str:
    """Prompt the user for a value, showing `default` (used if they just
    press Enter). Re-prompts if `validate(value)` returns an error string."""
    suffix = f" [{default}]" if default is not None else ""
    while True:
        answer = input(f"{question}{suffix}: ").strip()
        if not answer:
            if default is not None:
                answer = default
            else:
                print("  This value is required, please enter something.")
                continue
        if validate:
            error = validate(answer)
            if error:
                print(f"  {error}")
                continue
        return answer


def run_interactive() -> argparse.Namespace:
    print("=== scenic-pipeline-toolkit: interactive config setup ===")
    print("Press Enter to accept the default shown in [brackets].\n")

    data_dir = ask(
        "Folder with your data (loom, TF list, feather/tbl files)",
        validate=lambda v: None if Path(v).is_dir() else f"'{v}' is not a directory, try again.",
    )
    project = ask("Project name (groups related runs under artifacts/<project>/, e.g. 'canonical_tfs')")
    cell_line = input("Cell line (optional, e.g. 'HepG2'): ").strip() or None
    run_id = ask("Run ID (short name for this experiment, e.g. 'my_experiment')")
    replicates = ask(
        "Number of grn replicates (grnboost2 is stochastic; run it several times for robustness)",
        default="1",
        validate=lambda v: None if v.isdigit() and int(v) > 0 else "Must be a positive integer.",
    )
    num_workers = ask(
        "Number of workers",
        default="4",
        validate=lambda v: None if v.isdigit() and int(v) > 0 else "Must be a positive integer.",
    )
    nes_threshold = ask("NES threshold (used by ctx)", default="2.5")
    mode = ask("Dask mode (used by ctx)", default="dask_multiprocessing")
    method = ask("GRN method (used by grn)", default="grnboost2")
    outs_dir = ask("Output folder", default=str(artifact_dir_for(project, cell_line) / "outs"))

    return argparse.Namespace(
        data_dir=data_dir,
        project=project,
        cell_line=cell_line,
        run_id=run_id,
        replicates=int(replicates),
        no_seed=False,
        num_workers=int(num_workers),
        nes_threshold=nes_threshold,
        mode=mode,
        method=method,
        outs_dir=outs_dir,
        loom=None,
        tfs=None,
        baseline_feather=None,
        baseline_tbl=None,
        no_baseline=False,
        feather_regex=DEFAULT_FEATHER_REGEX,
        tbl_regex=DEFAULT_TBL_REGEX,
        grn_csv=None,
        ctx_csv=None,
    )


def find_one(data_dir: Path, pattern: str, kind: str, override: str | None) -> Path:
    if override:
        path = Path(override)
        if not path.is_file():
            sys.exit(f"ERROR: --{kind.lower().replace(' ', '-')} points to a file that doesn't exist: {path}")
        return path

    matches = sorted(data_dir.rglob(pattern))
    if len(matches) == 1:
        return matches[0]
    if len(matches) == 0:
        sys.exit(
            f"ERROR: no {kind} found under {data_dir} (looked for '{pattern}'). "
            f"Pass it explicitly with the matching flag."
        )
    sys.exit(
        f"ERROR: found {len(matches)} possible {kind} files under {data_dir}, expected exactly one:\n  "
        + "\n  ".join(str(m) for m in matches)
        + "\nPass the right one explicitly with the matching flag."
    )


def find_tf_files(data_dir: Path, extension: str, regex: str) -> dict[str, Path]:
    pattern = re.compile(regex)
    found: dict[str, Path] = {}
    for path in sorted(data_dir.rglob(f"*.{extension}")):
        m = pattern.search(path.name)
        if m:
            found[m.group(1)] = path
    return found


def find_baseline(data_dir: Path, extension: str, matched: set[Path], kind: str, override: str | None) -> Path | None:
    """Finds the plain, genome-wide feather/tbl (the one that ISN'T one of
    the per-TF files already matched by find_tf_files). Returns None if
    there isn't exactly one such file and no override was given — a
    baseline row is optional, so this never exits the program."""
    if override:
        path = Path(override)
        if not path.is_file():
            sys.exit(f"ERROR: --{kind} points to a file that doesn't exist: {path}")
        return path

    candidates = [p for p in sorted(data_dir.rglob(f"*.{extension}")) if p not in matched]
    if len(candidates) == 1:
        return candidates[0]
    if len(candidates) > 1:
        print(
            f"WARNING: found {len(candidates)} .{extension} file(s) that aren't tied to any TF, "
            f"expected at most one for the 'motifs_only' baseline — skipping it. "
            f"Pass --{kind} to pick one explicitly:\n  " + "\n  ".join(str(c) for c in candidates),
            file=sys.stderr,
        )
    return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--data-dir",
        help="folder to scan for loom/TF-list/feather/tbl files. "
        "Omit this (and every other flag) to be prompted interactively instead.",
    )
    parser.add_argument(
        "--project",
        help="groups related runs under artifacts/<project>/ (e.g. 'canonical_tfs'). "
        "Required alongside --data-dir in non-interactive mode.",
    )
    parser.add_argument("--cell-line", help="optional, e.g. 'HepG2' — included in the run folder name")
    parser.add_argument("--run-id", help="short name for this experiment, e.g. 'my_experiment'")
    parser.add_argument(
        "--replicates",
        type=int,
        default=1,
        help="number of independent grn runs (default: 1). Each replicate is crossed with every TF for ctx.",
    )
    parser.add_argument(
        "--no-seed",
        action="store_true",
        help="don't assign a --seed to grn (default: replicate i gets seed=i, so runs are reproducible "
        "while still being independent of each other; pass this to get pyscenic's own random-seed-per-run default instead).",
    )
    parser.add_argument("--num-workers", type=int, default=4, help="--num_workers for both grn and ctx (default: 4)")
    parser.add_argument("--nes-threshold", default="2.5", help="--nes_threshold for ctx (default: 2.5)")
    parser.add_argument("--mode", default="dask_multiprocessing", help="--mode for ctx (default: dask_multiprocessing)")
    parser.add_argument("--method", default="grnboost2", help="--method for grn (default: grnboost2)")
    parser.add_argument(
        "--outs-dir",
        help="base output folder for pyscenic's own outputs, adj/ and regs/ "
        "(default: artifacts/<project>/[<cell-line>/]outs/ — a sibling of that "
        "project's configs/ and logs/, so everything about it stays together)",
    )
    parser.add_argument("--loom", help="override: exact path to the .loom file (skip auto-discovery)")
    parser.add_argument("--tfs", help="override: exact path to the TF list .txt file (skip auto-discovery)")
    parser.add_argument("--baseline-feather", help="override: exact path to the genome-wide, non-per-TF .feather (skip auto-discovery)")
    parser.add_argument("--baseline-tbl", help="override: exact path to the genome-wide, non-per-TF .tbl (skip auto-discovery)")
    parser.add_argument(
        "--no-baseline",
        action="store_true",
        help="don't add a 'motifs_only' baseline row, even if a genome-wide feather+tbl pair is found",
    )
    parser.add_argument(
        "--feather-regex",
        default=DEFAULT_FEATHER_REGEX,
        help=r"regex with one capture group for the TF name, applied to .feather filenames "
        rf"(default: {DEFAULT_FEATHER_REGEX!r})",
    )
    parser.add_argument(
        "--tbl-regex",
        default=DEFAULT_TBL_REGEX,
        help=rf"regex with one capture group for the TF name, applied to .tbl filenames (default: {DEFAULT_TBL_REGEX!r})",
    )
    parser.add_argument("--grn-csv", help="override: exact output path for the grn CSV (skip the artifacts/<project>/<timestamp>/ layout)")
    parser.add_argument("--ctx-csv", help="override: exact output path for the ctx CSV (skip the artifacts/<project>/<timestamp>/ layout)")
    args = parser.parse_args()

    if args.data_dir is None:
        if not sys.stdin.isatty():
            parser.error("--data-dir is required when not running in an interactive terminal.")
        args = run_interactive()
    else:
        if args.run_id is None:
            parser.error("--run-id is required (or omit --data-dir too, to use interactive mode).")
        if args.project is None:
            parser.error("--project is required (or omit --data-dir too, to use interactive mode).")
        if args.outs_dir is None:
            args.outs_dir = str(artifact_dir_for(args.project, args.cell_line) / "outs")

    if args.replicates < 1:
        parser.error("--replicates must be a positive integer.")

    return args


def replicate_run_ids(run_id: str, replicates: int) -> list[str]:
    """Returns the run_id for each replicate. With replicates=1, the plain
    run_id is used unchanged (so single-replicate output filenames don't
    change); with more, each gets a zero-padded '_repNN' suffix."""
    if replicates == 1:
        return [run_id]
    width = max(2, len(str(replicates)))
    return [f"{run_id}_rep{i:0{width}d}" for i in range(1, replicates + 1)]


def main():
    args = parse_args()

    data_dir = Path(args.data_dir)
    if not data_dir.is_dir():
        sys.exit(f"ERROR: --data-dir is not a directory: {data_dir}")

    loom_path = find_one(data_dir, "*.loom", "loom", args.loom)
    tfs_path = find_one(data_dir, DEFAULT_TFS_GLOB, "TF list", args.tfs)

    feather_by_tf = find_tf_files(data_dir, "feather", args.feather_regex)
    tbl_by_tf = find_tf_files(data_dir, "tbl", args.tbl_regex)

    tfs_with_both = sorted(set(feather_by_tf) & set(tbl_by_tf))
    feather_only = sorted(set(feather_by_tf) - set(tbl_by_tf))
    tbl_only = sorted(set(tbl_by_tf) - set(feather_by_tf))

    if feather_only:
        print(f"WARNING: {len(feather_only)} TF(s) have a .feather but no matching .tbl, skipping: {', '.join(feather_only)}", file=sys.stderr)
    if tbl_only:
        print(f"WARNING: {len(tbl_only)} TF(s) have a .tbl but no matching .feather, skipping: {', '.join(tbl_only)}", file=sys.stderr)
    if not tfs_with_both:
        sys.exit("ERROR: no TF has both a .feather and a .tbl file — nothing to write to ctx_runs.local.csv.")

    baseline_feather = None
    baseline_tbl = None
    if not args.no_baseline:
        baseline_feather = find_baseline(data_dir, "feather", set(feather_by_tf.values()), "baseline-feather", args.baseline_feather)
        baseline_tbl = find_baseline(data_dir, "tbl", set(tbl_by_tf.values()), "baseline-tbl", args.baseline_tbl)
        if baseline_feather and not baseline_tbl:
            print(f"WARNING: found a baseline .feather ({baseline_feather}) but no baseline .tbl — skipping the 'motifs_only' row.", file=sys.stderr)
            baseline_feather = None
        elif baseline_tbl and not baseline_feather:
            print(f"WARNING: found a baseline .tbl ({baseline_tbl}) but no baseline .feather — skipping the 'motifs_only' row.", file=sys.stderr)
            baseline_tbl = None

    print(f"\nFound loom:          {loom_path}")
    print(f"Found TF list:       {tfs_path}")
    print(f"Found {len(tfs_with_both)} TF(s) with both feather+tbl: {', '.join(tfs_with_both)}")
    if baseline_feather:
        print(f"Found baseline (motifs_only) feather+tbl: {baseline_feather.name} + {baseline_tbl.name}")

    rep_ids = replicate_run_ids(args.run_id, args.replicates)
    if args.replicates > 1:
        print(f"Generating {args.replicates} grn replicate(s): {', '.join(rep_ids)}")

    # Every run adds a new timestamped file pair to a stable per-project
    # (optionally per-cell-line) folder — nothing is overwritten, so
    # artifacts/<project>/configs/ builds up a full, auditable history over
    # time. logs/ and outs/ (via --outs-dir's default, above) are siblings
    # of configs/ under that same project/cell-line folder, so everything
    # about one project stays together. --grn-csv/--ctx-csv (if given)
    # override this entirely, for edge cases.
    if args.project:
        artifact_dir = artifact_dir_for(args.project, args.cell_line)
        config_dir = artifact_dir / "configs"
        grn_filename, ctx_filename = config_filenames()
        grn_csv_path = Path(args.grn_csv) if args.grn_csv else config_dir / grn_filename
        ctx_csv_path = Path(args.ctx_csv) if args.ctx_csv else config_dir / ctx_filename
        print(f"Artifact folder:     {artifact_dir}")
    else:
        grn_csv_path = Path(args.grn_csv)
        ctx_csv_path = Path(args.ctx_csv)

    grn_csv_path.parent.mkdir(parents=True, exist_ok=True)
    with open(grn_csv_path, "w", newline="") as fh:
        # lineterminator="\n": csv.writer defaults to the 'excel' dialect,
        # which always writes "\r\n" regardless of open()'s newline="" — that
        # trailing \r would stick to the last field of each row (here, seed)
        # once read by bash's comma-only `IFS=',' read`, corrupting it.
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(["run_id", "loom_path", "tfs_path", "output_path", "num_workers", "method", "seed"])
        for i, rep_id in enumerate(rep_ids, start=1):
            grn_output = f"{args.outs_dir}/adj/{rep_id}.tsv"
            seed = "" if args.no_seed else i
            writer.writerow([rep_id, loom_path, tfs_path, grn_output, args.num_workers, args.method, seed])
    if args.no_seed:
        print(f"Wrote {grn_csv_path} ({len(rep_ids)} row(s), no seed — each run will use pyscenic's own random seed)")
    else:
        print(f"Wrote {grn_csv_path} ({len(rep_ids)} row(s), seed=1..{len(rep_ids)} for reproducibility)")

    ctx_csv_path.parent.mkdir(parents=True, exist_ok=True)
    n_ctx_rows = 0
    with open(ctx_csv_path, "w", newline="") as fh:
        # Same fix as the grn CSV above — otherwise a trailing \r corrupts
        # the last field of each row (here, output_path).
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(
            ["run_id", "tf_name", "adj_path", "feather_path", "tbl_path", "loom_path", "nes_threshold", "mode", "num_workers", "output_path"]
        )
        for rep_id in rep_ids:
            grn_output = f"{args.outs_dir}/adj/{rep_id}.tsv"

            if baseline_feather:
                row_id = f"{rep_id}_motifs_only"
                output_path = f"{args.outs_dir}/regs/{rep_id}/reg_motifs_only.csv"
                writer.writerow(
                    [row_id, "ALL", grn_output, baseline_feather, baseline_tbl, loom_path, args.nes_threshold, args.mode, args.num_workers, output_path]
                )
                n_ctx_rows += 1

            for tf in tfs_with_both:
                row_id = f"{rep_id}_{tf}"
                output_path = f"{args.outs_dir}/regs/{rep_id}/reg_{tf}.csv"
                writer.writerow(
                    [row_id, tf, grn_output, feather_by_tf[tf], tbl_by_tf[tf], loom_path, args.nes_threshold, args.mode, args.num_workers, output_path]
                )
                n_ctx_rows += 1
    print(f"Wrote {ctx_csv_path} ({n_ctx_rows} rows)")

    print()
    print("Next steps:")
    print(f"    bash scripts/run_pyscenic_grn.sh {grn_csv_path}")
    print(f"    bash scripts/run_pyscenic_ctx.sh {ctx_csv_path}")


if __name__ == "__main__":
    main()
